version: '3.8'

services:
  php:
    build: php
    container_name: "php"
    depends_on:
      - db
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
    environment: # Fields for Laravel .env
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=akash
      - DB_PASSWORD=root
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: webserver
    environment:
      TZ: "Asia/Dhaka"
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: db
    restart: "on-failure"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: akash
      MYSQL_PASSWORD: root
      TZ: "Asia/Dhaka"
    ports:
      - "3306:3306"
    volumes:
      - ../database:/workspace/database
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
    working_dir: /workspace/database  
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: akash
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
